### ISSUE TITLE
absurd colors of image overlay used during web cam stream

### ISSUE THREAD

**Issue by IbrahimAliAsghar** [free5lot/Camera_Net#5]
when i am using the image overlay in camera overlay its is getting absurd color combination, can u please check into it. 
here is my code to draw the image 
```
`string filepath = @"E:\office\lux desktop app\Camera_Net-master\Camera_Net-master\Samples\CameraControlTool\water_PNG3290.png";
`
                Bitmap bitmap1 = new Bitmap(filepath);
                g.DrawImage(bitmap1, new Rectangle(400 , 0, 250, 600));
```
and here is the image the comes after
![water](https://user-images.githubusercontent.com/7556725/27897530-446615a6-623a-11e7-903d-3dd0da337e52.PNG)

and this the orignal image

![water_png3290](https://user-images.githubusercontent.com/7556725/27897519-329dc346-623a-11e7-861e-ebed271a464c.png)

**Comment by free5lot** [comment]
Hi @IbrahimAliAsghar , please tell does the sample code with colored text work fine on your configuration (camera+computer)? You can change to color of font and check if it is the same as you expected.
If the sample code works fine, then the problem is about how you make an overlay image.

For me it looks like this issue is related to alpha channel, try to remove it.
Please note that alpha channel with partial opacity (not binary) is only supported in the code of direct3d overlay and you may be using another one with a image of non-binary opacity.
