### ISSUE TITLE
getting Bitmap from Camera

### ISSUE THREAD

**Issue by Prakash19921206** [free5lot/Camera_Net#6]
hi
is there a way to get Bitmap from `Camera_NET.cameraControl`?
because i wanted to stretch fit the video/image on winform like we can do using `pictureBox`

Thanks

**Comment by free5lot** [comment]
Yes, there are 2 ways to get Image or Bitmap from CameraControl. Look up the example provided.

**Comment by Prakash19921206** [comment]
hi @free5lot ,
Thank you for your reply. 
i'm new to C#, i looked into the [sample code](https://github.com/free5lot/Camera_Net/tree/master/Samples), in winform designer `Camera_NET.cameraControl` is used to display the video (which do not need Bitmap). 


i didn't find [sample project ](https://github.com/free5lot/Camera_Net/tree/master/Samples)using Bitmap, if we get in Bitmap it would be easy to add text or graphics over it using .net framework. 
i found snapshot method returning `Bitmap `[here ](https://github.com/free5lot/Camera_Net/blob/master/Camera_Net/Public/Camera.cs#L868)and [here](https://github.com/free5lot/Camera_Net/blob/master/Camera_Net/Public/Camera.cs#L933)
can you direct me to the sample code?

Thanks & Regards

**Comment by free5lot** [comment]
Bitmap is a result of snapshot, it is gotten from SampleGrabber filter. But you can't make bitmaps for every frame and use it as output replacing images, because it will be too slow and the whole Direct3D/DirectShow hardware support won't be working to your advantage.
Maybe I got you wrong, because I was referring to getting Bitmaps with either of two functions SnapshotSourceImage() or SnapshotOutputImage(). If this functions are ok for you, look at this example of use:
https://github.com/free5lot/Camera_Net/blob/master/Samples/CameraControlTool/FormCameraControlTool.cs#L147
Hope it helped.

**Comment by Prakash19921206** [comment]
is there any alternative way to use DirectShow and get Bitmap at lowest latency ?

**Comment by free5lot** [comment]
One more time, you want to get a single or several Bitmaps (like 1-2 per second) or all frames (like 25 frames per second)?

**Comment by Prakash19921206** [comment]
25 fps. i suppose its not possible with `DirectShow `with `Bitmap`?

**Comment by free5lot** [comment]
If you want every frame (25fps) to Bitmap then you can get it in SampleGrabber callback function, it got every frame as a memory block, and you can convert it to Bitmap, the same way the library does.
https://github.com/free5lot/Camera_Net/blob/master/Camera_Net/Internal/SampleGrabberHelper.cs#L161
Not very easy.

When you copy this memory to Bitmap and draw it by yourself (like putting it into PictureBox) it will be processed by CPU (without hardware acceleration) and therefore can take some computer significant CPU resources to do it (depends on cpu model, image size, framerate).

**Comment by Prakash19921206** [comment]
Ok
Thank you

**Comment by free5lot** [comment]
You're welcome.
