### ISSUE TITLE
Cannot change camera output settings in CameraControlTool

### ISSUE THREAD

**Issue by codec-abc** [free5lot/Camera_Net#7]
Hi,

For my project I need to capture the camera stream at decent resolution (something near 1M pixels) and framerate (30 fps at least) to run some image processing/analysis on it and once done inject the stream into 3D rendering pipeline. To do this task this project seems great. So far, I have played with the sample "CameraControlTool" and while I can choose the camera and its resolution I cannot validate any change done in the popup that appear when I click the "Camera Output Settings" button. This is problematic because in order to get a decent resolution (1280x720) at 30 fps it appears that I need to set the ouput color space (or compression) to MJPG. The other combination of settings does not seems to allow that much frames per second at this resolution. When I try to apply my changes in this popup I got an error popup saying "Error Connecting... This format is not currently available". And any change would trigger this error message too. Even opening the settings popup, leaving the default values as they are and clicking Ok brings this error popup

Do you have any idea what can cause this and how can I solve it ?

**Comment by codec-abc** [comment]
I have played a little more with DirectShow and particularly with GraphEdit. I was able to reproduce the issue in GraphEdit. For that I created a simple graph with a VideoCapture node and appropriate output (Graph edit insert automatically the conversions' nodes where needed). Once connected, if I right click the VideoCapture pin and try to set the resolution I got the same error message (as you can see in the capture).
![failedchangeresolution](https://user-images.githubusercontent.com/1208646/29401700-8d2d65b4-8332-11e7-97e2-9f910475f9bd.PNG)

After some quick Google research I found [this link](https://social.msdn.microsoft.com/Forums/en-US/d6cd1e0a-3b58-4f34-8ca7-c21d934cf049/graphedit-unable-to-set-image-size-for-microsoft-lifecam-cinema?forum=windowsdirectshowdevelopment). Basically, it tell that this happen because I need to change the pin properties (like resolution and framerate) **before** connecting them. So I removed the links, changed the resolution and connected them back again and it worked! To sum up, I think I am not able to change the capture resolution in the CameraControlTool because the capture graph is probably already connected and need to be disconnected to allow to do so.

**Comment by free5lot** [comment]
First of all, I would recommend GraphStudioNext as a good replacement for outdated and buggy GraphEdit. https://github.com/cplussharp/graph-studio-next

Secondly, it's good you found the problem.
It's strange that the driver of your camera does not support resolution change after graph build. Maybe it's because the resolution affects the intermediate filters between output pin and render pin. Do you have different blocks (automatically added) for different resolutions? 
By the way, use VMR9 (VideoMixingRenderer9) instead of Video Renderer if you need any overlay/mixing stuff.

**Comment by codec-abc** [comment]
Thanks for taking time to answer me.

I tested with GraphStudioNext (thanks for the tips about the depecrated GraphEdit by the way) and the behavior is the same. It happens with a usb Microsoft LifeCam HD-3000 too. And I tested on another computer on Windows 10 and I got the same issue. So, I guess the issue is relatively common.

EDIT: 
About your question, I **do** have different blocks for different resolutions, which should explain why I have got an error why I try to change resolution at runtime

Ideally, I would like to be able to iterate through all the capture mode available (a mix of resolution, framerate & encoding) for a camera, have some "business" logic to decide which is the best. Then, start the capture and have a callback for each new image where I can process it (Implying that the buffer should be easily exploitable (so preferably not encoded, or in a format that I can convert it to something like rgb888 quickly). Do you think this is achievable and if yes have you any advice/samples to get me started?

**Comment by codec-abc** [comment]
After modifying the sample I managed to get it running at 1280x720 at 30 fps. To do that, I modified the Resolution class to include the framerate and the encoding. Otherwise those 2 cases are considered equals:
* 1280x720 @ 10 FPS encoded in YUY2
* 1280x720 @ 30 FPS encoded in MJPG

Because the 10 FPS YUY2 appears first in the output format list, the 30 FPS MJPG format has no chance to end up in the same list.

Since the "capture" graph is recreated each time the resolution selected change this change works nicely. I don't know it is worth updating the sample for that but I think a note in the Readme (I could do a pull request if you agree) cool help beginners like me.

Otherwise, I plan to use this library for a game in Unity and as such I would like to not have UI and to not rely on Win32 nor WPF. Is there a headless sample somewhere to get me started? Lastly, I saw that there is a ISampleGrabberCB interface to process the data of the camera (which I need to do), but it would help me save some CPU time if it were possible to have the buffer encoded in YUV format (like 4:2:0 for example). Do you have some documentation to point me in order to achieve that?

**Comment by free5lot** [comment]
> Then, start the capture and have a callback for each new image where I can process it (Implying that the buffer should be easily exploitable (so preferably not encoded, or in a format that I can convert it to something like rgb888 quickly). Do you think this is achievable and if yes have you any advice/samples to get me started?

It's possible, you should use ISampleGrabberCB.SampleCB() function, it get every frame not-encoded but as a memory buffer. 
https://github.com/free5lot/Camera_Net/blob/master/Camera_Net/Internal/SampleGrabberHelper.cs#L161
You can get every frame and analyse it, but be accurate, it comes from another thread, not in main gui thread, so you have to sync threads if you want to send the image from it to the gui. Analyse the code in the library, because it uses this and converts memory buffer to the Image, but single one and you would need every frame.

About PR with description of resolutions override - you may create one. Unfortunatly it seems I don't have camera with such resolution/framerate override, otherwise I could fix it myself by modifying Resolution class and List creation process.

**Comment by codec-abc** [comment]
Thanks again for the answer. [I made some changes here](https://github.com/codec-abc/Camera_Net/commit/50283996282d365cef8e99d33a978f25e75f2229). I am not sure that they are really clean so if you want that I do a pull request I recommend that you look at the diff before and tell me if this is ok. As an example that changes the sample from
![old](https://user-images.githubusercontent.com/1208646/29516066-424f9ef0-866f-11e7-9f4e-7751ac1f4fe9.png)
to
![new](https://user-images.githubusercontent.com/1208646/29516074-4993e5d6-866f-11e7-8ba7-bae16b355367.png)

Since the issue I opened concerned only this part I think I gonna close it after you answered about the pull request.

Still I might need your advices one last time but I don't think it's worth to open an issue just for that so I will ask here. I tried to make a sample in Unity but it did not work properly so to work around that I start a windowless app (from Unity) whose purpose is to stream locally the image buffer acquired in the callback. It seems to work quite well. (By the way, a windowless camera stream could be a nice addition to the samples, my solution seems quite hackish to be honest) But I did not anticipated that the buffer conversion would take so much time. For my needs I would like to get the image in "a YUV format", (and I need the luminance channel to **not** be interleaved with the U and V channels. On the other hand, the U and V channels interleaving and order doesn't matter.) I guess it may be possible to insert a BGR888-> YUV filter in the capture graph but I really don't know much about DirectShow. So, do you know if there is a (preferably easy) way to do that ?

**Comment by free5lot** [comment]
About code - thank you, I will take a look probably in a week.

About you question - I don't know, read more about SampleGrabber filter, maybe you can change its format and the pin automatic connection will do the rest, but I don't know about it. And the buffer conversion was expected to be slow, because it is done on CPU without video card hardware support.
